#!/usr/bin/env bash
# bench-chain-cpu.sh — how many movy tracks can run a given synth, at a given
# polyphony, before the audio frame overruns?
#
# WHAT THE LIMIT ACTUALLY IS. Not a number this script invents: the shim defines
# `OVERRUN_THRESHOLD_US 2850` ("98% of budget", schwung_shim.c:4357) for the
# whole SPI frame, counts breaches as `overruns=`, and starts SKIPPING DSP work
# once they persist. So the ceiling is the frame total, and a run that reports
# any overrun has already failed regardless of what the averages say.
#
# METHOD. Measuring every (module, polyphony, chain-count) combination would take
# hours of device time, so this measures the SLOPE and extrapolates:
#
#   1. baseline frame total with no movy chains loaded
#   2. load the module into $CHAINS chains
#   3. for 1..4 held notes per chain: sound them, settle, read the frame total
#   4. per-chain cost = (total - baseline) / CHAINS
#   5. max tracks = (2850 - baseline) / per-chain cost
#
# Notes are held (note-on with no note-off) so the voices stay active while the
# frame is sampled — a struck-and-released note would be measuring silence.
#
# Usage: ./scripts/bench-chain-cpu.sh [move.local] [chains] [module ...]
set -uo pipefail
cd "$(dirname "$0")/.."

HOST="${1:-move.local}"; shift || true
CHAINS="${1:-4}"; shift || true
MODULES=("$@")
[ ${#MODULES[@]} -eq 0 ] && MODULES=(plaits obxd dexed noisemaker helm forge weird-dreams surge)

MOVY_DIR="$(pwd)"
# shellcheck source=lib/test-set.sh
source "$MOVY_DIR/scripts/lib/test-set.sh"
LOG=/data/UserData/schwung/debug.log
# Work budget per frame, MEASURED not assumed (scripts/measure-work-ceiling.sh,
# recorded in docs/chain-cpu-benchmarks.md): `total` frame time stays flat while
# the ioctl wait absorbs added work, and breaks away once work passes ~2000us.
# The frame is 2900us but most of that is the wait, so neither 2900 nor the
# shim's 2850us total-threshold is a work budget. Override to re-derive.
WORK_BUDGET="${WORK_BUDGET:-2000}"
SETTLE=12                   # seconds of frames to average over
PITCHES=(60 64 67 71)       # a chord, not one note four times

BLD=$'\033[1m'; RST=$'\033[0m'; YEL=$'\033[1;33m'

ssh -o ConnectTimeout=5 "ableton@$HOST" true 2>/dev/null || {
    echo "DEVICE OFFLINE — cannot benchmark"; exit 1
}
ssh "ableton@$HOST" 'touch /data/UserData/schwung/debug_log_on'

ep() { node scripts/engine-param.mjs set "$1" "$2" "$HOST" >/dev/null 2>&1; }

# WORK per frame = pre + post, in microseconds.
#
# NOT `total`: total is pre + ioctl + post, and the ioctl is mostly the blocking
# WAIT for the next SPI frame. That wait shrinks as work grows, so total sits at
# ~2660us no matter how many chains are loaded — measuring it "proves" chains are
# free. Movy's chain rendering lands in POST (shadow_inprocess_render_to_buffer);
# `pre` is the shim's own per-frame work.
work_avg() {
    ssh "ableton@$HOST" "grep -o 'Frame(us):.*' $LOG | tail -n 6" \
        | awk '{ pre=0; post=0;
                 for (i=1;i<=NF;i++) {
                     if ($i=="pre") { split($(i+1),a,"="); pre=a[2]+0 }
                     if ($i=="post") { split($(i+1),b,"="); post=b[2]+0 }
                 }
                 s += pre+post; n++ }
             END { print (n? int(s/n):0) }'
}
post_avg() {
    ssh "ableton@$HOST" "grep -o 'Frame(us):.*' $LOG | tail -n 6" \
        | awk '{ for (i=1;i<=NF;i++) if ($i=="post") { split($(i+1),b,"="); s+=b[2]+0; n++ } }
             END { print (n? int(s/n):0) }'
}
# Overruns are CUMULATIVE since boot, so only the delta across the window means
# anything. An absolute reading of 1.1 million is just uptime.
overrun_delta() {
    ssh "ableton@$HOST" "grep -o 'overruns=[0-9]*' $LOG | tail -n 6" \
        | awk -F= 'NR==1 { first=$2+0 } { last=$2+0 } END { print (last-first)+0 }'
}

clear_chains() {
    for i in $(seq 0 11); do ep "ch$i:synth:module" ""; done
}
notes() {  # notes <count> <on|off>
    local count="$1" onoff="$2" status
    [ "$onoff" = on ] && status=144 || status=128
    for c in $(seq 0 $((CHAINS-1))); do
        for n in $(seq 0 $((count-1))); do
            # dots, not commas: ch<N>:midi is "status.d1.d2" (parse_midi_triplet)
            ep "ch$c:midi" "$status.${PITCHES[$n]}.100"
        done
    done
}

OUT=docs/chain-cpu-benchmarks.md
{
echo "# Movy chain CPU benchmarks"
echo
echo "How many movy-hosted tracks can run a given synth, at a given polyphony,"
echo "before the audio frame overruns."
echo
echo "Generated by \`scripts/bench-chain-cpu.sh\` on \`$(date +%Y-%m-%d)\`."
echo
echo "## The limit"
echo
echo "The ceiling is not a number chosen here. The shim defines"
echo "\`OVERRUN_THRESHOLD_US 2850\` — 98% of the 2900 µs frame budget for 128"
echo "frames at 44.1 kHz (\`schwung_shim.c:4357\`) — counts breaches as"
echo "\`overruns=\`, and begins **skipping DSP work** once they persist. Any"
echo "measurement reporting an overrun has already failed."
echo
echo "\`max tracks\` below is \`(2850 − baseline) / per-chain cost\`, measured at"
echo "$CHAINS loaded chains and extrapolated. Notes are **held**, so the voices are"
echo "actually running while the frame is sampled."
echo
echo "> These are movy-hosted tracks (5-16) only. Tracks 1-4 are Schwung's own and"
echo "> cost movy nothing — they are rendered by the host, not by movy."
echo
} > "$OUT"

echo "${BLD}=== chain CPU benchmark ===${RST}"
echo "host=$HOST chains=$CHAINS work-budget=${WORK_BUDGET}us"
echo "modules: ${MODULES[*]}"

clear_chains
ssh "ableton@$HOST" "> $LOG"; sleep "$SETTLE"
BASE_WORK=$(work_avg); BASE_POST=$(post_avg)
echo
echo "baseline (no movy chains): work=${BASE_WORK}us (post=${BASE_POST}us)"
{
echo "Baseline with no movy chains loaded: **${BASE_WORK} µs** of work per frame"
echo '(`pre` + `post`), of which `post` — where movy renders — is '"${BASE_POST}"' µs.'
echo
echo "| module | notes/track | work/frame | per track | max tracks | overruns |"
echo "|---|---|---|---|---|---|"
} >> "$OUT"

for MOD in "${MODULES[@]}"; do
    echo
    echo "${BLD}--- $MOD ---${RST}"
    clear_chains; sleep 2
    for c in $(seq 0 $((CHAINS-1))); do ep "ch$c:synth:module" "$MOD"; done
    sleep $((CHAINS + 4))

    if ! ssh "ableton@$HOST" "cat $LOG" | qgrep "chain 0: synth = $MOD"; then
        echo "${YEL}  could not load $MOD — skipping${RST}"
        echo "| \`$MOD\` | — | — | — | — | did not load |" >> "$OUT"
        continue
    fi

    for N in 1 2 3 4; do
        notes "$N" on
        ssh "ableton@$HOST" "> $LOG"; sleep "$SETTLE"
        WORK=$(work_avg); OVR=$(overrun_delta)
        notes "$N" off
        sleep 1

        DELTA=$((WORK - BASE_WORK))
        if [ "$DELTA" -gt 0 ]; then
            PER=$((DELTA / CHAINS))
            [ "$PER" -lt 1 ] && PER=1
            MAXTR=$(( (WORK_BUDGET - BASE_WORK) / PER ))
            [ "$MAXTR" -gt 12 ] && MAXTR=12
        else
            PER=0; MAXTR=12
        fi
        printf '  %-14s %d note(s): work=%sus per-track=%sus -> %s tracks%s\n' \
            "$MOD" "$N" "$WORK" "$PER" "$MAXTR" \
            "$([ "$OVR" -gt 0 ] && echo "  OVERRUNS +$OVR")"
        printf '| `%s` | %d | %s µs | %s µs | **%s** | %s |\n' \
            "$MOD" "$N" "$WORK" "$([ "$PER" -eq 0 ] && echo "<1" || echo "$PER")" \
            "$([ "$MAXTR" -ge 12 ] && echo "12 (all)" || echo "$MAXTR")" \
            "$([ "$OVR" -gt 0 ] && echo "**+$OVR**" || echo "0")" >> "$OUT"
    done
done

clear_chains
{
echo
echo "## Reading this"
echo
echo "- **max tracks** is capped at 12: movy hosts twelve chains, so \"12 (all)\""
echo "  means the synth is not the constraint."
echo "- **per-chain** is the frame-total delta divided by the loaded chain count."
echo "  A \`<1\` means the cost was below this counter's resolution."
echo "- **overruns** must be 0. A non-zero value means the frame budget was"
echo "  breached during the measurement and the shim was already dropping DSP"
echo "  work — that row is a failure, not a data point."
echo "- Loading is far more expensive than running: a single module load blocks"
echo "  the callback for ~1986 µs (\`scripts/measure-load-blocking.sh\`), which is"
echo "  why movy releases at most one load per audio callback."
echo
} >> "$OUT"

echo
echo "${BLD}wrote $OUT${RST}"
